-- ============================================================================
-- REEMPLAZAR ESPACIOS COMUNES
-- Base de datos: jwmantto
-- Fecha: 2025-12-29
-- ============================================================================
-- Este script elimina los espacios comunes actuales y los reemplaza con nuevos datos
-- IMPORTANTE: Asegúrate de tener un backup antes de ejecutar este script
-- ============================================================================

BEGIN;

-- Paso 1: Eliminar todos los espacios comunes actuales
-- NOTA: Esto eliminará también los mantenimientos asociados (CASCADE)
DELETE FROM espacios_comunes;

-- Paso 2: Resetear la secuencia del ID
ALTER SEQUENCE espacios_comunes_id_seq RESTART WITH 1;

-- Paso 3: Insertar los nuevos espacios comunes
INSERT INTO espacios_comunes (
    nombre, 
    edificio_id, 
    tipo, 
    descripcion, 
    estado, 
    capacidad, 
    horario_apertura, 
    horario_cierre,
    activo
) VALUES
    ('VESTIDOR CABALLEROS', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-VESTIDC', 'disponible', NULL, NULL, NULL, true),
    ('BANO CABALLEROS COLABORADORES', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-VESTIDC-BCCOLA', 'disponible', NULL, NULL, NULL, true),
    ('VESTIDOR DAMAS', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-VESTIDD', 'disponible', NULL, NULL, NULL, true),
    ('BANO DAMAS COLABORADORAS', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-VESTIDD-BDCOLA', 'disponible', NULL, NULL, NULL, true),
    ('BODEGA AREAS PUBLICAS', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-BODAPUB', 'disponible', NULL, NULL, NULL, true),
    ('COCINA BANQUETES', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-COCBANQ', 'disponible', NULL, NULL, NULL, true),
    ('AREA DESCAMOCHE BANQUETES', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-COCBANQ-AREDBQ', 'disponible', NULL, NULL, NULL, true),
    ('OFICINA CHIEF', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-COCBANQ-OFICHI', 'disponible', NULL, NULL, NULL, true),
    ('PASILLO BANQUETES', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-COCBANQ-PASIBQ', 'disponible', NULL, NULL, NULL, true),
    ('COCINA GENERAL', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-COCGRAL', 'disponible', NULL, NULL, NULL, true),
    ('CHOCOLATERIA', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-COCGRAL-CHOCOL', 'disponible', NULL, NULL, NULL, true),
    ('OFICINA DE CAPITANES', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-COCGRAL-OFICAP', 'disponible', NULL, NULL, NULL, true),
    ('OFICINA DE CHEF', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-COCGRAL-OFICHE', 'disponible', NULL, NULL, NULL, true),
    ('PASTELERIA UA', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-COCGRAL-PASTUA', 'disponible', NULL, NULL, NULL, true),
    ('ROOM SERVICE', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-COCGRAL-ROMSER', 'disponible', NULL, NULL, NULL, true),
    ('COMEDOR DE EMPLEADOS', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-COMEDOR', 'disponible', NULL, NULL, NULL, true),
    ('CONSULTORIO MEDICO', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-CMEDICO', 'disponible', NULL, NULL, NULL, true),
    ('CUARTOS DE FILTROS', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-CUARFLT', 'disponible', NULL, NULL, NULL, true),
    ('CARCAMO RETROLAVADO 01', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-CUARFLT-CRCMR1', 'disponible', NULL, NULL, NULL, true),
    ('CUARTO DE FILTRO ADOLESCENTES', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-CUARFLT-CFLADO', 'disponible', NULL, NULL, NULL, true),
    ('CUARTO DE FILTRO ADULTOS', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-CUARFLT-CFLADT', 'disponible', NULL, NULL, NULL, true),
    ('CUARTO DE FILTRO CDA', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-CUARFLT-CFLCDA', 'disponible', NULL, NULL, NULL, true),
    ('CUARTO DE FILTRO FAM 3', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-CUARFLT-CFLFM3', 'disponible', NULL, NULL, NULL, true),
    ('CUARTO DE FILTRO SPA', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-CUARFLT-CFLSPA', 'disponible', NULL, NULL, NULL, true),
    ('ESTACIONAMIENTO', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-ESTACIO', 'disponible', NULL, NULL, NULL, true),
    ('BODEGA DE PINTORES', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-ESTACIO-BODPIN', 'disponible', NULL, NULL, NULL, true),
    ('CUARTO DE FILTRO CABINA 12', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-ESTACIO-CFLC12', 'disponible', NULL, NULL, NULL, true),
    ('CUARTO DE MAQUINAS AGUA CALIENTE SPA', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-ESTACIO-CTOMCS', 'disponible', NULL, NULL, NULL, true),
    ('TALLER DE CARPINTERIA', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-ESTACIO-TLLCAR', 'disponible', NULL, NULL, NULL, true),
    ('LAVANDERIA', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-LAVANDE', 'disponible', NULL, NULL, NULL, true),
    ('BODEGA LOST AND FOUND', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-LAVANDE-BODLAF', 'disponible', NULL, NULL, NULL, true),
    ('OFICINA AMA DE LLAVES', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-LAVANDE-OFIALL', 'disponible', NULL, NULL, NULL, true),
    ('OFICINA SASTRE', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-LAVANDE-OFISAS', 'disponible', NULL, NULL, NULL, true),
    ('SHUT PRINCIPAL LAVANDERIA', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-LAVANDE-SHUTLV', 'disponible', NULL, NULL, NULL, true),
    ('AREA DE VALET', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-LAVANDE-AREVAL', 'disponible', NULL, NULL, NULL, true),
    ('OFICINA PREVENCION', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-OFIPREV', 'disponible', NULL, NULL, NULL, true),
    ('CASETA PREVENCION', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-OFIPREV-CASPRV', 'disponible', NULL, NULL, NULL, true),
    ('CCTV PREVENCION', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-OFIPREV-CCTVPR', 'disponible', NULL, NULL, NULL, true),
    ('AREA DE MANIOBRAS', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-AREMANI', 'disponible', NULL, NULL, NULL, true),
    ('BODEGA PAPELERIA ALMACEN GRAL', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-AREMANI-BODPAG', 'disponible', NULL, NULL, NULL, true),
    ('BODEGA STEWARD', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-AREMANI-BODSTW', 'disponible', NULL, NULL, NULL, true),
    ('OFICINA COMPRAS', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-AREMANI-OFICOM', 'disponible', NULL, NULL, NULL, true),
    ('RECEPCION DE MERCANCIA', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-AREMANI-RECMER', 'disponible', NULL, NULL, NULL, true),
    ('BANO CABALLEROS PROVEEDORES', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-AREMANI-BCPROV', 'disponible', NULL, NULL, NULL, true),
    ('MEZZANINE RH', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-MEZZORH', 'disponible', NULL, NULL, NULL, true),
    ('OFICINA RECURSOS HUMANOS', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-OFIREHU', 'disponible', NULL, NULL, NULL, true),
    ('AREA DE TANQUES ESTACIONARIOS', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-ARETANE', 'disponible', NULL, NULL, NULL, true),
    ('ESCALERAS ACCESO TANQUES LP', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-ARETANE-ESATLP', 'disponible', NULL, NULL, NULL, true),
    ('AREA DE PTAR', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-AREPTAR', 'disponible', NULL, NULL, NULL, true),
    ('CARCAMO AMORTIGUAMIENTO PREAEREACION', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-AREPTAR-CRCMPA', 'disponible', NULL, NULL, NULL, true),
    ('CARCAMO DE DERRAME', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-AREPTAR-CRCMDR', 'disponible', NULL, NULL, NULL, true),
    ('CARCAMOS AGUAS CRUDAS PRINCIPAL', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-AREPTAR-CRCMAC', 'disponible', NULL, NULL, NULL, true),
    ('AREA ESTABILIZACION DE LODOS', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-AREPTAR-AREEDL', 'disponible', NULL, NULL, NULL, true),
    ('AREA MINICELL-10 MNC-10', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-AREPTAR-AREMNC', 'disponible', NULL, NULL, NULL, true),
    ('AREA PLATAFORMA QUIMICOS', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-AREPTAR-AREPDQ', 'disponible', NULL, NULL, NULL, true),
    ('AREA REACTOR BIOLOGICO AEROBICO', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-AREPTAR-ARERBA', 'disponible', NULL, NULL, NULL, true),
    ('AREA REACTOR ZONA ANOXICA', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-AREPTAR-ARERZA', 'disponible', NULL, NULL, NULL, true),
    ('SALA DE MAQUINAS', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-SMAQPPL', 'disponible', NULL, NULL, NULL, true),
    ('AREA BOMBAS DE CONDENSADO', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-SMAQPPL-AREBCD', 'disponible', NULL, NULL, NULL, true),
    ('AREA CALENTADORES', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-SMAQPPL-ARECAL', 'disponible', NULL, NULL, NULL, true),
    ('AREA CHILLERS', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-SMAQPPL-ARECHI', 'disponible', NULL, NULL, NULL, true),
    ('AREA EQUIPO CONTRA INCENDIO', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-SMAQPPL-AREECI', 'disponible', NULL, NULL, NULL, true),
    ('AREA OSMOSIS', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-SMAQPPL-AREOSM', 'disponible', NULL, NULL, NULL, true),
    ('AREA PLANTAS DE EMERGENCIA', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-SMAQPPL-AREPLE', 'disponible', NULL, NULL, NULL, true),
    ('AREA SISTEMA HIDRONEUMATICO', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-SMAQPPL-ARESIH', 'disponible', NULL, NULL, NULL, true),
    ('AREA TANQUES DE AGUA CALIENTE', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-SMAQPPL-ARETAC', 'disponible', NULL, NULL, NULL, true),
    ('AREA TREN DE FILTRADO', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-SMAQPPL-ARETRF', 'disponible', NULL, NULL, NULL, true),
    ('CISTERNA 113 M3 AUX POTABLE 1', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-SMAQPPL-CISPO1', 'disponible', NULL, NULL, NULL, true),
    ('CISTERNA 113 M3 AUX POTABLE 2', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-SMAQPPL-CISPO2', 'disponible', NULL, NULL, NULL, true),
    ('CISTERNA 187 M3 AGUA SALADA', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-SMAQPPL-CISASL', 'disponible', NULL, NULL, NULL, true),
    ('CISTERNA 207 M3 PCI 1', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-SMAQPPL-CISCI1', 'disponible', NULL, NULL, NULL, true),
    ('CISTERNA 207 M3 PCI 2', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-SMAQPPL-CISCI2', 'disponible', NULL, NULL, NULL, true),
    ('CISTERNA 240 M3 TRATADA 1', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-SMAQPPL-CISTR1', 'disponible', NULL, NULL, NULL, true),
    ('CISTERNA 240 M3 TRATADA 2', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-SMAQPPL-CISTR2', 'disponible', NULL, NULL, NULL, true),
    ('CISTERNA 353 M3 AGUA POTABLE 1', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-SMAQPPL-CISAP1', 'disponible', NULL, NULL, NULL, true),
    ('CISTERNA 353 M3 AGUA POTABLE 2', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-SMAQPPL-CISAP2', 'disponible', NULL, NULL, NULL, true),
    ('SUBESTACIONES ELECTRICAS', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-SUBESEL', 'disponible', NULL, NULL, NULL, true),
    ('SUBESTACION 1', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-SUBESEL-SUBES1', 'disponible', NULL, NULL, NULL, true),
    ('SUBESTACION 2', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-SUBESEL-SUBES2', 'disponible', NULL, NULL, NULL, true),
    ('SUBESTACION 3', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-SUBESEL-SUBES3', 'disponible', NULL, NULL, NULL, true),
    ('SUBESTACION 4', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-SUBESEL-SUBES4', 'disponible', NULL, NULL, NULL, true),
    ('SUBESTACION 5', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-SUBESEL-SUBES5', 'disponible', NULL, NULL, NULL, true),
    ('SUBESTACION 6', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-SUBESEL-SUBES6', 'disponible', NULL, NULL, NULL, true),
    ('SUBESTACION 7', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-SUBESEL-SUBES7', 'disponible', NULL, NULL, NULL, true),
    ('SUBESTACION PRINCIPAL', 1, 'comun', 'Código técnico: J-LO-ECHA-PBBOH-SUBESEL-SUBESP', 'disponible', NULL, NULL, NULL, true),
    ('NIVEL 1C', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV1C', 'disponible', NULL, NULL, NULL, true),
    ('JARDINES FRONTALES EDIF CHARLY', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV1C-JARCHAR', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C101', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV1C-HAB3101', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C102', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV1C-HAB3102', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C103', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV1C-HAB3103', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C104', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV1C-HAB3104', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C105', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV1C-HAB3105', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C106', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV1C-HAB3106', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C107', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV1C-HAB3107', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C108', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV1C-HAB3108', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C109', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV1C-HAB3109', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C110', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV1C-HAB3110', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C111', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV1C-HAB3111', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C112', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV1C-HAB3112', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C113', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV1C-HAB3113', 'disponible', NULL, NULL, NULL, true),
    ('ROPERIA NIVEL 1C', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV1C-ROP1CHA', 'disponible', NULL, NULL, NULL, true),
    ('PANTRY DELY', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV1C-PANTRYD', 'disponible', NULL, NULL, NULL, true),
    ('NIVEL 2C', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV2C', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C201', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV2C-HAB3201', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C202', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV2C-HAB3202', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C203', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV2C-HAB3203', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C204', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV2C-HAB3204', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C205', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV2C-HAB3205', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C206', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV2C-HAB3206', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C207', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV2C-HAB3207', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C208', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV2C-HAB3208', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C209', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV2C-HAB3209', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C210', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV2C-HAB3210', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C211', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV2C-HAB3211', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C212', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV2C-HAB3212', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C213', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV2C-HAB3213', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C214', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV2C-HAB3214', 'disponible', NULL, NULL, NULL, true),
    ('ROPERIA NIVEL 2C', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV2C-ROP2CHA', 'disponible', NULL, NULL, NULL, true),
    ('NIVEL 3C', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV3C', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C301', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV3C-HAB3301', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C302', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV3C-HAB3302', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C303', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV3C-HAB3303', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C304', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV3C-HAB3304', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C305', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV3C-HAB3305', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C306', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV3C-HAB3306', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C307', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV3C-HAB3307', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C308', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV3C-HAB3308', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C309', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV3C-HAB3309', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C310', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV3C-HAB3310', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C311', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV3C-HAB3311', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C312', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV3C-HAB3312', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C313', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV3C-HAB3313', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C314', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV3C-HAB3314', 'disponible', NULL, NULL, NULL, true),
    ('ROPERIA NIVEL 3C', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV3C-ROP3CHA', 'disponible', NULL, NULL, NULL, true),
    ('NIVEL 4C', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV4C', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C401', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV4C-HAB3401', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C402', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV4C-HAB3402', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C403', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV4C-HAB3403', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C404', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV4C-HAB3404', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C405', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV4C-HAB3405', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C406', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV4C-HAB3406', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C407', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV4C-HAB3407', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C408', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV4C-HAB3408', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C409', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV4C-HAB3409', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C410', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV4C-HAB3410', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C411', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV4C-HAB3411', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C412', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV4C-HAB3412', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C413', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV4C-HAB3413', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION C414', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV4C-HAB3414', 'disponible', NULL, NULL, NULL, true),
    ('ROPERIA NIVEL 4C', 1, 'comun', 'Código técnico: J-LO-ECHA-NIV4C-ROP4CHA', 'disponible', NULL, NULL, NULL, true),
    ('MOTOR LOBBY', 1, 'comun', 'Código técnico: J-LO-MBBY', 'disponible', NULL, NULL, NULL, true),
    ('NIVEL 1 LOBBY', 1, 'comun', 'Código técnico: J-LO-MBBY-NIV1L', 'disponible', NULL, NULL, NULL, true),
    ('ANDADOR DE ACCESO VEHICULOS', 1, 'comun', 'Código técnico: J-LO-MBBY-NIV1L-PASIVEH', 'disponible', NULL, NULL, NULL, true),
    ('AUKA DELI', 1, 'comun', 'Código técnico: J-LO-MBBY-NIV1L-AUKADEL', 'disponible', NULL, NULL, NULL, true),
    ('BAR NIPARAYA', 1, 'comun', 'Código técnico: J-LO-MBBY-NIV1L-BARNIPA', 'disponible', NULL, NULL, NULL, true),
    ('BIBLIOTECA', 1, 'comun', 'Código técnico: J-LO-MBBY-NIV1L-BIBLIOT', 'disponible', NULL, NULL, NULL, true),
    ('BOUTIQUE', 1, 'comun', 'Código técnico: J-LO-MBBY-NIV1L-BOUTIQU', 'disponible', NULL, NULL, NULL, true),
    ('LOBBY DE GRUPOS', 1, 'comun', 'Código técnico: J-LO-MBBY-NIV1L-LOBBYGP', 'disponible', NULL, NULL, NULL, true),
    ('LOBBY PRINCIPAL', 1, 'comun', 'Código técnico: J-LO-MBBY-NIV1L-LOBBYPP', 'disponible', NULL, NULL, NULL, true),
    ('BANO CABALLEROS LOBBY', 1, 'comun', 'Código técnico: J-LO-MBBY-NIV1L-LOBBYPP-BCLOBB', 'disponible', NULL, NULL, NULL, true),
    ('BANO DAMAS LOBBY', 1, 'comun', 'Código técnico: J-LO-MBBY-NIV1L-LOBBYPP-BDLOBB', 'disponible', NULL, NULL, NULL, true),
    ('MURO LOBBY PRINCIPAL', 1, 'comun', 'Código técnico: J-LO-MBBY-NIV1L-MRLPPAL', 'disponible', NULL, NULL, NULL, true),
    ('OFICINA BELL BOY', 1, 'comun', 'Código técnico: J-LO-MBBY-NIV1L-OFIBBOY', 'disponible', NULL, NULL, NULL, true),
    ('OFICINA RECEPCION', 1, 'comun', 'Código técnico: J-LO-MBBY-NIV1L-OFIRECE', 'disponible', NULL, NULL, NULL, true),
    ('OFICINA TAXIS', 1, 'comun', 'Código técnico: J-LO-MBBY-NIV1L-OFITAXI', 'disponible', NULL, NULL, NULL, true),
    ('BANO CABALLEROS TAXIS', 1, 'comun', 'Código técnico: J-LO-MBBY-NIV1L-OFITAXI-BCTAXI', 'disponible', NULL, NULL, NULL, true),
    ('RECEPCION', 1, 'comun', 'Código técnico: J-LO-MBBY-NIV1L-RECEPCI', 'disponible', NULL, NULL, NULL, true),
    ('OFICINA TAMARAL', 1, 'comun', 'Código técnico: J-LO-MBBY-NIV1L-OFITAMA', 'disponible', NULL, NULL, NULL, true),
    ('EDIFICIO ECO', 1, 'comun', 'Código técnico: J-LO-EECO', 'disponible', NULL, NULL, NULL, true),
    ('FACHADA ECO', 1, 'comun', 'Código técnico: J-LO-EECO-FAEXE', 'disponible', NULL, NULL, NULL, true),
    ('AZOTEA ECO', 1, 'comun', 'Código técnico: J-LO-EECO-AZECO', 'disponible', NULL, NULL, NULL, true),
    ('PLANTA BAJA ECO', 1, 'comun', 'Código técnico: J-LO-EECO-PBECO', 'disponible', NULL, NULL, NULL, true),
    ('OFICINAS ADMINISTRATIVAS', 1, 'comun', 'Código técnico: J-LO-EECO-PBECO-OFIADMS', 'disponible', NULL, NULL, NULL, true),
    ('AREA COMUN', 1, 'comun', 'Código técnico: J-LO-EECO-PBECO-OFIADMS-ARECOM', 'disponible', NULL, NULL, NULL, true),
    ('OFICINA AT YOU SERVICE', 1, 'comun', 'Código técnico: J-LO-EECO-PBECO-OFIADMS-OFIAYS', 'disponible', NULL, NULL, NULL, true),
    ('OFICINA AUDITORIA GRUPOS', 1, 'comun', 'Código técnico: J-LO-EECO-PBECO-OFIADMS-OFIAUG', 'disponible', NULL, NULL, NULL, true),
    ('OFICINA BODAS', 1, 'comun', 'Código técnico: J-LO-EECO-PBECO-OFIADMS-OFIBOD', 'disponible', NULL, NULL, NULL, true),
    ('BODEGA ROOM SERVICE', 1, 'comun', 'Código técnico: J-LO-EECO-PBECO-OFIADMS-BODRMS', 'disponible', NULL, NULL, NULL, true),
    ('OFICINA C X P', 1, 'comun', 'Código técnico: J-LO-EECO-PBECO-OFIADMS-OFICXP', 'disponible', NULL, NULL, NULL, true),
    ('CAJA GENERAL', 1, 'comun', 'Código técnico: J-LO-EECO-PBECO-OFIADMS-CAJGRA', 'disponible', NULL, NULL, NULL, true),
    ('AREA CONTRALORIA', 1, 'comun', 'Código técnico: J-LO-EECO-PBECO-OFIADMS-ARECON', 'disponible', NULL, NULL, NULL, true),
    ('OFICINA DIRECCION GENERAL', 1, 'comun', 'Código técnico: J-LO-EECO-PBECO-OFIADMS-OFIDIG', 'disponible', NULL, NULL, NULL, true),
    ('OFICINA GERENTE AYB', 1, 'comun', 'Código técnico: J-LO-EECO-PBECO-OFIADMS-OFIGAB', 'disponible', NULL, NULL, NULL, true),
    ('OFICINA BANQUETES', 1, 'comun', 'Código técnico: J-LO-EECO-PBECO-OFIADMS-OFIBQT', 'disponible', NULL, NULL, NULL, true),
    ('OFICINA CONTRALOR', 1, 'comun', 'Código técnico: J-LO-EECO-PBECO-OFIADMS-OFICTR', 'disponible', NULL, NULL, NULL, true),
    ('OFICINA RESERVACIONES', 1, 'comun', 'Código técnico: J-LO-EECO-PBECO-OFIADMS-OFIRES', 'disponible', NULL, NULL, NULL, true),
    ('OFICINA REVENUE', 1, 'comun', 'Código técnico: J-LO-EECO-PBECO-OFIADMS-OFIREV', 'disponible', NULL, NULL, NULL, true),
    ('OFICINA REVENUE MANAGER', 1, 'comun', 'Código técnico: J-LO-EECO-PBECO-OFIADMS-OFIREM', 'disponible', NULL, NULL, NULL, true),
    ('OFICINA SUBCONTRALOR', 1, 'comun', 'Código técnico: J-LO-EECO-PBECO-OFIADMS-OFISUC', 'disponible', NULL, NULL, NULL, true),
    ('OFICINA VENTAS 1', 1, 'comun', 'Código técnico: J-LO-EECO-PBECO-OFIADMS-OFIVT1', 'disponible', NULL, NULL, NULL, true),
    ('OFICINA VENTAS 2', 1, 'comun', 'Código técnico: J-LO-EECO-PBECO-OFIADMS-OFIVT2', 'disponible', NULL, NULL, NULL, true),
    ('OFICINA VENTAS 3', 1, 'comun', 'Código técnico: J-LO-EECO-PBECO-OFIADMS-OFIVT3', 'disponible', NULL, NULL, NULL, true),
    ('OFICINA VENTAS DIRECCION', 1, 'comun', 'Código técnico: J-LO-EECO-PBECO-OFIADMS-OFIVTD', 'disponible', NULL, NULL, NULL, true),
    ('BANO CABALLEROS ADMON', 1, 'comun', 'Código técnico: J-LO-EECO-PBECO-OFIADMS-BCADMN', 'disponible', NULL, NULL, NULL, true),
    ('BANO DAMAS ADMON', 1, 'comun', 'Código técnico: J-LO-EECO-PBECO-OFIADMS-BDADMN', 'disponible', NULL, NULL, NULL, true),
    ('OFICINA DE SISTEMAS', 1, 'comun', 'Código técnico: J-LO-EECO-PBECO-OFISIST', 'disponible', NULL, NULL, NULL, true),
    ('AREA BANCO DE BATERIAS', 1, 'comun', 'Código técnico: J-LO-EECO-PBECO-OFISIST-AREBDB', 'disponible', NULL, NULL, NULL, true),
    ('AREA TV', 1, 'comun', 'Código técnico: J-LO-EECO-PBECO-OFISIST-ARETVS', 'disponible', NULL, NULL, NULL, true),
    ('AREA SITE SISTEMAS', 1, 'comun', 'Código técnico: J-LO-EECO-PBECO-OFISIST-ARESIS', 'disponible', NULL, NULL, NULL, true),
    ('NIVEL 1E', 1, 'comun', 'Código técnico: J-LO-EECO-NIV1E', 'disponible', NULL, NULL, NULL, true),
    ('ANDADOR ECO A FOX', 1, 'comun', 'Código técnico: J-LO-EECO-NIV1E-PASIECO', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E101', 1, 'comun', 'Código técnico: J-LO-EECO-NIV1E-HAB5101', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E102', 1, 'comun', 'Código técnico: J-LO-EECO-NIV1E-HAB5102', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E103', 1, 'comun', 'Código técnico: J-LO-EECO-NIV1E-HAB5103', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E104', 1, 'comun', 'Código técnico: J-LO-EECO-NIV1E-HAB5104', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E105', 1, 'comun', 'Código técnico: J-LO-EECO-NIV1E-HAB5105', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E106', 1, 'comun', 'Código técnico: J-LO-EECO-NIV1E-HAB5106', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E107', 1, 'comun', 'Código técnico: J-LO-EECO-NIV1E-HAB5107', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E108', 1, 'comun', 'Código técnico: J-LO-EECO-NIV1E-HAB5108', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E109', 1, 'comun', 'Código técnico: J-LO-EECO-NIV1E-HAB5109', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E110', 1, 'comun', 'Código técnico: J-LO-EECO-NIV1E-HAB5110', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E111', 1, 'comun', 'Código técnico: J-LO-EECO-NIV1E-HAB5111', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E112', 1, 'comun', 'Código técnico: J-LO-EECO-NIV1E-HAB5112', 'disponible', NULL, NULL, NULL, true),
    ('ROPERIA NIVEL 1E', 1, 'comun', 'Código técnico: J-LO-EECO-NIV1E-ROP1ECO', 'disponible', NULL, NULL, NULL, true),
    ('NIVEL 2E', 1, 'comun', 'Código técnico: J-LO-EECO-NIV2E', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E201', 1, 'comun', 'Código técnico: J-LO-EECO-NIV2E-HAB5201', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E202', 1, 'comun', 'Código técnico: J-LO-EECO-NIV2E-HAB5202', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E203', 1, 'comun', 'Código técnico: J-LO-EECO-NIV2E-HAB5203', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E204', 1, 'comun', 'Código técnico: J-LO-EECO-NIV2E-HAB5204', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E205', 1, 'comun', 'Código técnico: J-LO-EECO-NIV2E-HAB5205', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E206', 1, 'comun', 'Código técnico: J-LO-EECO-NIV2E-HAB5206', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E207', 1, 'comun', 'Código técnico: J-LO-EECO-NIV2E-HAB5207', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E208', 1, 'comun', 'Código técnico: J-LO-EECO-NIV2E-HAB5208', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E209', 1, 'comun', 'Código técnico: J-LO-EECO-NIV2E-HAB5209', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E210', 1, 'comun', 'Código técnico: J-LO-EECO-NIV2E-HAB5210', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E211', 1, 'comun', 'Código técnico: J-LO-EECO-NIV2E-HAB5211', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E212', 1, 'comun', 'Código técnico: J-LO-EECO-NIV2E-HAB5212', 'disponible', NULL, NULL, NULL, true),
    ('ROPERIA NIVEL 2E', 1, 'comun', 'Código técnico: J-LO-EECO-NIV2E-ROP2ECO', 'disponible', NULL, NULL, NULL, true),
    ('NIVEL 3E', 1, 'comun', 'Código técnico: J-LO-EECO-NIV3E', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E301', 1, 'comun', 'Código técnico: J-LO-EECO-NIV3E-HAB5301', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E302', 1, 'comun', 'Código técnico: J-LO-EECO-NIV3E-HAB5302', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E303', 1, 'comun', 'Código técnico: J-LO-EECO-NIV3E-HAB5303', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E304', 1, 'comun', 'Código técnico: J-LO-EECO-NIV3E-HAB5304', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E305', 1, 'comun', 'Código técnico: J-LO-EECO-NIV3E-HAB5305', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E306', 1, 'comun', 'Código técnico: J-LO-EECO-NIV3E-HAB5306', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E307', 1, 'comun', 'Código técnico: J-LO-EECO-NIV3E-HAB5307', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E308', 1, 'comun', 'Código técnico: J-LO-EECO-NIV3E-HAB5308', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E309', 1, 'comun', 'Código técnico: J-LO-EECO-NIV3E-HAB5309', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E310', 1, 'comun', 'Código técnico: J-LO-EECO-NIV3E-HAB5310', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E311', 1, 'comun', 'Código técnico: J-LO-EECO-NIV3E-HAB5311', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E312', 1, 'comun', 'Código técnico: J-LO-EECO-NIV3E-HAB5312', 'disponible', NULL, NULL, NULL, true),
    ('ROPERIA NIVEL 3E', 1, 'comun', 'Código técnico: J-LO-EECO-NIV3E-ROP3ECO', 'disponible', NULL, NULL, NULL, true),
    ('NIVEL 4E', 1, 'comun', 'Código técnico: J-LO-EECO-NIV4E', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E401', 1, 'comun', 'Código técnico: J-LO-EECO-NIV4E-HAB5401', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E402', 1, 'comun', 'Código técnico: J-LO-EECO-NIV4E-HAB5402', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E403', 1, 'comun', 'Código técnico: J-LO-EECO-NIV4E-HAB5403', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E404', 1, 'comun', 'Código técnico: J-LO-EECO-NIV4E-HAB5404', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E405', 1, 'comun', 'Código técnico: J-LO-EECO-NIV4E-HAB5405', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E406', 1, 'comun', 'Código técnico: J-LO-EECO-NIV4E-HAB5406', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E407', 1, 'comun', 'Código técnico: J-LO-EECO-NIV4E-HAB5407', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E408', 1, 'comun', 'Código técnico: J-LO-EECO-NIV4E-HAB5408', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E409', 1, 'comun', 'Código técnico: J-LO-EECO-NIV4E-HAB5409', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E410', 1, 'comun', 'Código técnico: J-LO-EECO-NIV4E-HAB5410', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E411', 1, 'comun', 'Código técnico: J-LO-EECO-NIV4E-HAB5411', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION E412', 1, 'comun', 'Código técnico: J-LO-EECO-NIV4E-HAB5412', 'disponible', NULL, NULL, NULL, true),
    ('ROPERIA NIVEL 4E', 1, 'comun', 'Código técnico: J-LO-EECO-NIV4E-ROP4ECO', 'disponible', NULL, NULL, NULL, true),
    ('EDIFICIO FOX', 1, 'comun', 'Código técnico: J-LO-EFOX', 'disponible', NULL, NULL, NULL, true),
    ('FACHADA FOX', 1, 'comun', 'Código técnico: J-LO-EFOX-FAEXF', 'disponible', NULL, NULL, NULL, true),
    ('AZOTEA FOX', 1, 'comun', 'Código técnico: J-LO-EFOX-AZFOX', 'disponible', NULL, NULL, NULL, true),
    ('NIVEL 1F', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV1F', 'disponible', NULL, NULL, NULL, true),
    ('JARDINES FRONTALES FOX', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV1F-JARFFOX', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F101', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV1F-HAB6101', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F102', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV1F-HAB6102', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F103', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV1F-HAB6103', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F104', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV1F-HAB6104', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F105', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV1F-HAB6105', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F106', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV1F-HAB6106', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F107', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV1F-HAB6107', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F108', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV1F-HAB6108', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F109', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV1F-HAB6109', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F110', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV1F-HAB6110', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F111', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV1F-HAB6111', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F112', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV1F-HAB6112', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F113', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV1F-HAB6113', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F114 SUITE', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV1F-HAB6114', 'disponible', NULL, NULL, NULL, true),
    ('ROPERIA NIVEL 1F', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV1F-ROP1FOX', 'disponible', NULL, NULL, NULL, true),
    ('NIVEL 2F', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV2F', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F201', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV2F-HAB6201', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F202', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV2F-HAB6202', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F203', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV2F-HAB6203', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F204', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV2F-HAB6204', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F205', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV2F-HAB6205', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F206', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV2F-HAB6206', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F207', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV2F-HAB6207', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F208', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV2F-HAB6208', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F209', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV2F-HAB6209', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F210', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV2F-HAB6210', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F211', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV2F-HAB6211', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F212', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV2F-HAB6212', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F213', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV2F-HAB6213', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F214 SUITE', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV2F-HAB6214', 'disponible', NULL, NULL, NULL, true),
    ('ROPERIA NIVEL 2F', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV2F-ROP2FOX', 'disponible', NULL, NULL, NULL, true),
    ('NIVEL 3F', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV3F', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F301', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV3F-HAB6301', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F302', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV3F-HAB6302', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F303', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV3F-HAB6303', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F304', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV3F-HAB6304', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F305', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV3F-HAB6305', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F306', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV3F-HAB6306', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F307', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV3F-HAB6307', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F308', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV3F-HAB6308', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F309', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV3F-HAB6309', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F310', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV3F-HAB6310', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F311', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV3F-HAB6311', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F312', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV3F-HAB6312', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F313', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV3F-HAB6313', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F314 SUITE', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV3F-HAB6314', 'disponible', NULL, NULL, NULL, true),
    ('ROPERIA NIVEL 3F', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV3F-ROP3FOX', 'disponible', NULL, NULL, NULL, true),
    ('NIVEL 4F', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV4F', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F401', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV4F-HAB6401', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F402', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV4F-HAB6402', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F403', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV4F-HAB6403', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F404', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV4F-HAB6404', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F405', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV4F-HAB6405', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F406', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV4F-HAB6406', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F407', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV4F-HAB6407', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F408', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV4F-HAB6408', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F409', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV4F-HAB6409', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F410', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV4F-HAB6410', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F411', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV4F-HAB6411', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F412', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV4F-HAB6412', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F413', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV4F-HAB6413', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION F414 SUITE', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV4F-HAB6414', 'disponible', NULL, NULL, NULL, true),
    ('ROPERIA NIVEL 4F', 1, 'comun', 'Código técnico: J-LO-EFOX-NIV4F-ROP4FOX', 'disponible', NULL, NULL, NULL, true),
    ('AREAS GENERALES RESORT', 1, 'comun', 'Código técnico: J-LO-AGER', 'disponible', NULL, NULL, NULL, true),
    ('NIVEL 01 AREAS RESORT', 1, 'comun', 'Código técnico: J-LO-AGER-NIV01', 'disponible', NULL, NULL, NULL, true),
    ('AREA DE PLAYA', 1, 'comun', 'Código técnico: J-LO-AGER-NIV01-AREPLAY', 'disponible', NULL, NULL, NULL, true),
    ('ESCALERAS ACCESO PLAYA', 1, 'comun', 'Código técnico: J-LO-AGER-NIV01-ESACPLA', 'disponible', NULL, NULL, NULL, true),
    ('DUELA PLAYA', 1, 'comun', 'Código técnico: J-LO-AGER-NIV01-DUELPLA', 'disponible', NULL, NULL, NULL, true),
    ('NIVEL 0 AREAS RESORT', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R', 'disponible', NULL, NULL, NULL, true),
    ('ALBERCAS', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-ALBERCS', 'disponible', NULL, NULL, NULL, true),
    ('AREA ALBERCA ADOLESCENTES', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-AREADOL', 'disponible', NULL, NULL, NULL, true),
    ('ALBERCA ADOLESCENTES', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-AREADOL-ALBADO', 'disponible', NULL, NULL, NULL, true),
    ('ESCALERAS DE ACCESO LADO UA ADOLESCENTES', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-AREADOL-ESADOL', 'disponible', NULL, NULL, NULL, true),
    ('AREA ALBERCA ADULTOS', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-AREADTO', 'disponible', NULL, NULL, NULL, true),
    ('ALBERCA ADULTOS', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-AREADTO-ALBADT', 'disponible', NULL, NULL, NULL, true),
    ('DUELA ADULTOS', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-AREADTO-DUELAD', 'disponible', NULL, NULL, NULL, true),
    ('JACUZZI ADULTOS', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-AREADTO-JACADT', 'disponible', NULL, NULL, NULL, true),
    ('AREA ALBERCA FAM 1', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-AREFAM1', 'disponible', NULL, NULL, NULL, true),
    ('ALBERCA FAM 1', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-AREFAM1-ALBFM1', 'disponible', NULL, NULL, NULL, true),
    ('AREA ALBERCA FAM 2', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-AREFAM2', 'disponible', NULL, NULL, NULL, true),
    ('ALBERCA FAM 2', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-AREFAM2-ALBFM2', 'disponible', NULL, NULL, NULL, true),
    ('AREA ALBERCA FAM 3', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-AREFAM3', 'disponible', NULL, NULL, NULL, true),
    ('ALBERCA FAM 3', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-AREFAM3-ALBFM3', 'disponible', NULL, NULL, NULL, true),
    ('CANAL INFINITY', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-AREFAM3-CANINF', 'disponible', NULL, NULL, NULL, true),
    ('JACUZZI FAM III', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-AREFAM3-JACFM3', 'disponible', NULL, NULL, NULL, true),
    ('AREA ALBERCA KIDS 1', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-AREKID1', 'disponible', NULL, NULL, NULL, true),
    ('ALBERCA KIDS 1', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-AREKID1-ALBKD1', 'disponible', NULL, NULL, NULL, true),
    ('AREA ALBERCA KIDS 2', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-AREKID2', 'disponible', NULL, NULL, NULL, true),
    ('ALBERCA KIDS 2', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-AREKID2-ALBKD2', 'disponible', NULL, NULL, NULL, true),
    ('AREA ALBERCA MARHUMO', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-AREMARH', 'disponible', NULL, NULL, NULL, true),
    ('ALBERCA MARHUMO', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-AREMARH-ALBMAH', 'disponible', NULL, NULL, NULL, true),
    ('BAR MARHUMO', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-AREMARH-BARMAH', 'disponible', NULL, NULL, NULL, true),
    ('RESTAURANT MARHUMO', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-AREMARH-RESTMH', 'disponible', NULL, NULL, NULL, true),
    ('AREA ALBERCA SALADA', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-ARESALA', 'disponible', NULL, NULL, NULL, true),
    ('ALBERCA SALADA', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-ARESALA-ALBSAL', 'disponible', NULL, NULL, NULL, true),
    ('CARCAMO PLUVIAL AREA SALADA', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-ARESALA-CRCMPS', 'disponible', NULL, NULL, NULL, true),
    ('CUARTO DE FILTRO SALADA', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-ARESALA-CFLSAL', 'disponible', NULL, NULL, NULL, true),
    ('DUELA SALADA', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-ARESALA-DUELSA', 'disponible', NULL, NULL, NULL, true),
    ('ESCALERAS ALBERCA SALADA', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-ARESALA-ESALBS', 'disponible', NULL, NULL, NULL, true),
    ('BANO CABALLEROS SALADA', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-ARESALA-BCALBS', 'disponible', NULL, NULL, NULL, true),
    ('BANO DAMAS SALADA', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-ARESALA-BDALBS', 'disponible', NULL, NULL, NULL, true),
    ('BAR KAHA', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-BARKAHA', 'disponible', NULL, NULL, NULL, true),
    ('PASILLO Y ESCALERAS KAHA', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-BARKAHA-PASIEK', 'disponible', NULL, NULL, NULL, true),
    ('SITE KAHA BAR', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-BARKAHA-SITEKB', 'disponible', NULL, NULL, NULL, true),
    ('BANO CABALLEROS KAHA', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-BARKAHA-BCKBAR', 'disponible', NULL, NULL, NULL, true),
    ('BANO CABALLEROS KAHA COLABORADORES', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-BARKAHA-BCKABC', 'disponible', NULL, NULL, NULL, true),
    ('BANO DAMAS KAHA', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-BARKAHA-BDKBAR', 'disponible', NULL, NULL, NULL, true),
    ('BUSINESS CENTER', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-BUSCENT', 'disponible', NULL, NULL, NULL, true),
    ('SALA DE JUNTAS BOARD ROOM', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-BUSCENT-SALJUN', 'disponible', NULL, NULL, NULL, true),
    ('BODEGA AYB BC', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-BUSCENT-BODABC', 'disponible', NULL, NULL, NULL, true),
    ('ESPEJO MATKUS', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-BUSCENT-ESPMAT', 'disponible', NULL, NULL, NULL, true),
    ('SALON MATKU I', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-BUSCENT-SLNMK1', 'disponible', NULL, NULL, NULL, true),
    ('SALON MATKU II', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-BUSCENT-SLNMK2', 'disponible', NULL, NULL, NULL, true),
    ('SALON MATKU III', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-BUSCENT-SLNMK3', 'disponible', NULL, NULL, NULL, true),
    ('SALON MATKU IV', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-BUSCENT-SLNMK4', 'disponible', NULL, NULL, NULL, true),
    ('RECEPCION BUSINESS CENTER', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-BUSCENT-RECEPB', 'disponible', NULL, NULL, NULL, true),
    ('SALA DE COMPUTADORAS BUSINESS CENTER', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-BUSCENT-SALCBC', 'disponible', NULL, NULL, NULL, true),
    ('BANO CABALLEROS BUSINESS C', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-BUSCENT-BCBUSC', 'disponible', NULL, NULL, NULL, true),
    ('BANO DAMAS BUSINESS C', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-BUSCENT-BDBUSC', 'disponible', NULL, NULL, NULL, true),
    ('CANCHA DE TENIS', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-CANDTEN', 'disponible', NULL, NULL, NULL, true),
    ('BANO DAMAS CANCHA DE TENIS', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-CANDTEN-BDTENI', 'disponible', NULL, NULL, NULL, true),
    ('ESPEJO KAHA BAR', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-ESPKAHA', 'disponible', NULL, NULL, NULL, true),
    ('JARDIN HUNDIDO', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-JARHUND', 'disponible', NULL, NULL, NULL, true),
    ('RESTAURANT TACOS EL LUCHADOR', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-JARHUND-RESTLU', 'disponible', NULL, NULL, NULL, true),
    ('MIMAH FITNESS CENTER', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-GYMFITC', 'disponible', NULL, NULL, NULL, true),
    ('GIMNASIO', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-GYMFITC-GYMNAC', 'disponible', NULL, NULL, NULL, true),
    ('JARDIN YOGA', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-GYMFITC-JARYOG', 'disponible', NULL, NULL, NULL, true),
    ('OFICINA GYM', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-GYMFITC-OFICGY', 'disponible', NULL, NULL, NULL, true),
    ('BANO CABALLEROS GYM', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-GYMFITC-BCFITC', 'disponible', NULL, NULL, NULL, true),
    ('BANO DAMAS GYM', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-GYMFITC-BDFITC', 'disponible', NULL, NULL, NULL, true),
    ('NAYAA KOT KIDS CORNER', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-NYKKIDC', 'disponible', NULL, NULL, NULL, true),
    ('CINE KIDS', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-NYKKIDC-CINKID', 'disponible', NULL, NULL, NULL, true),
    ('KIDS CLUB', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-NYKKIDC-KIDCLB', 'disponible', NULL, NULL, NULL, true),
    ('TEENS CLUB', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-NYKKIDC-TEENSC', 'disponible', NULL, NULL, NULL, true),
    ('BANO CABALLEROS KIDS CORNER', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-NYKKIDC-BCKIDS', 'disponible', NULL, NULL, NULL, true),
    ('BANO DAMAS KIDS CORNER', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-NYKKIDC-BDKIDS', 'disponible', NULL, NULL, NULL, true),
    ('PATIO AMET', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-PATAMET', 'disponible', NULL, NULL, NULL, true),
    ('PASILLO DERECHO AMET', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-PATAMET-PASIAD', 'disponible', NULL, NULL, NULL, true),
    ('PASILLO IZQUIERDO AMET', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-PATAMET-PASIAI', 'disponible', NULL, NULL, NULL, true),
    ('SALONES MILA', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-SLNMILA', 'disponible', NULL, NULL, NULL, true),
    ('CUARTO DE MAQUINAS ECO', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-SLNMILA-CTOMEC', 'disponible', NULL, NULL, NULL, true),
    ('FOYER NORTE', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-SLNMILA-FOYRNT', 'disponible', NULL, NULL, NULL, true),
    ('FOYER SUR', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-SLNMILA-FOYRSR', 'disponible', NULL, NULL, NULL, true),
    ('SALON MILA 1-2', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-SLNMILA-SLNML1', 'disponible', NULL, NULL, NULL, true),
    ('SALON MILA 3', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-SLNMILA-SLNML3', 'disponible', NULL, NULL, NULL, true),
    ('SALON MILA 4', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-SLNMILA-SLNML4', 'disponible', NULL, NULL, NULL, true),
    ('SALON MILA 5-6', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-SLNMILA-SLNML5', 'disponible', NULL, NULL, NULL, true),
    ('SALON MIMU', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-SLNMILA-SLNMIM', 'disponible', NULL, NULL, NULL, true),
    ('SALON MITAT', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-SLNMILA-SLNMIT', 'disponible', NULL, NULL, NULL, true),
    ('OFICINA VENTAS BANQUETES', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-SLNMILA-OFIVTB', 'disponible', NULL, NULL, NULL, true),
    ('BANO CABALLEROS FOYER', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-SLNMILA-BCFOYR', 'disponible', NULL, NULL, NULL, true),
    ('BANO DAMAS FOYER', 1, 'comun', 'Código técnico: J-LO-AGER-NIV0R-SLNMILA-BDFOYR', 'disponible', NULL, NULL, NULL, true),
    ('NIVEL 1 AREAS RESORT', 1, 'comun', 'Código técnico: J-LO-AGER-NIV1R', 'disponible', NULL, NULL, NULL, true),
    ('ANFITEATRO SUM SAN', 1, 'comun', 'Código técnico: J-LO-AGER-NIV1R-ANFITEA', 'disponible', NULL, NULL, NULL, true),
    ('BAR PEYOTE', 1, 'comun', 'Código técnico: J-LO-AGER-NIV1R-BARPEYO', 'disponible', NULL, NULL, NULL, true),
    ('ESPEJO PRINCIPAL', 1, 'comun', 'Código técnico: J-LO-AGER-NIV1R-ESPPPAL', 'disponible', NULL, NULL, NULL, true),
    ('KEPE GAZEBO', 1, 'comun', 'Código técnico: J-LO-AGER-NIV1R-KEPEGAZ', 'disponible', NULL, NULL, NULL, true),
    ('RESTAURANT UA', 1, 'comun', 'Código técnico: J-LO-RTUA', 'disponible', NULL, NULL, NULL, true),
    ('NIVEL 1 RESTAURANT UA', 1, 'comun', 'Código técnico: J-LO-RTUA-NIV1U', 'disponible', NULL, NULL, NULL, true),
    ('AREA BUFFET DESAYUNO', 1, 'comun', 'Código técnico: J-LO-RTUA-NIV1U-AREBUFD', 'disponible', NULL, NULL, NULL, true),
    ('CAJA UA', 1, 'comun', 'Código técnico: J-LO-RTUA-NIV1U-CAJARUA', 'disponible', NULL, NULL, NULL, true),
    ('CARNICERIA UA', 1, 'comun', 'Código técnico: J-LO-RTUA-NIV1U-CARNRUA', 'disponible', NULL, NULL, NULL, true),
    ('HUERTO ORGANICO', 1, 'comun', 'Código técnico: J-LO-RTUA-NIV1U-HUERORG', 'disponible', NULL, NULL, NULL, true),
    ('JARDINERA FRONTAL UA', 1, 'comun', 'Código técnico: J-LO-RTUA-NIV1U-JARFRUA', 'disponible', NULL, NULL, NULL, true),
    ('LINEA CALIENTE', 1, 'comun', 'Código técnico: J-LO-RTUA-NIV1U-LINEACA', 'disponible', NULL, NULL, NULL, true),
    ('LINEA FRIA', 1, 'comun', 'Código técnico: J-LO-RTUA-NIV1U-LINEAFR', 'disponible', NULL, NULL, NULL, true),
    ('TERRAZA UA', 1, 'comun', 'Código técnico: J-LO-RTUA-NIV1U-TZAREUA', 'disponible', NULL, NULL, NULL, true),
    ('MEZZANINNE RESTAURANT UA', 1, 'comun', 'Código técnico: J-LO-RTUA-NIV1U-MEZZAUA', 'disponible', NULL, NULL, NULL, true),
    ('SPA JASHA', 1, 'comun', 'Código técnico: J-LO-SJAS', 'disponible', NULL, NULL, NULL, true),
    ('NIVEL 1 SPA', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S', 'disponible', NULL, NULL, NULL, true),
    ('ALBERCA VITALITY', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-ALBVITA', 'disponible', NULL, NULL, NULL, true),
    ('AREA DE SERVICIO', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-ARESERV', 'disponible', NULL, NULL, NULL, true),
    ('AREA DESCANSO MASAJISTAS', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-AREMASJ', 'disponible', NULL, NULL, NULL, true),
    ('AREA RELAJACION CABALLEROS', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-ARERELC', 'disponible', NULL, NULL, NULL, true),
    ('JACUZZI HOMBRES CALIENTE', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-ARERELC-JACCAC', 'disponible', NULL, NULL, NULL, true),
    ('JACUZZI HOMBRES FRIO', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-ARERELC-JACCAF', 'disponible', NULL, NULL, NULL, true),
    ('MURO LLORON CABALLEROS', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-ARERELC-MRLLOC', 'disponible', NULL, NULL, NULL, true),
    ('BANO CABALLEROS SPA', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-ARERELC-BCJSPA', 'disponible', NULL, NULL, NULL, true),
    ('AREA RELAJACION DAMAS', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-ARERELD', 'disponible', NULL, NULL, NULL, true),
    ('JACUZZI MUJERES CALIENTE', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-ARERELD-JACDAC', 'disponible', NULL, NULL, NULL, true),
    ('JACUZZI MUJERES FRIO', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-ARERELD-JACDAF', 'disponible', NULL, NULL, NULL, true),
    ('MURO LLORON DAMAS', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-ARERELD-MRLLOD', 'disponible', NULL, NULL, NULL, true),
    ('BANO DAMAS SPA', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-ARERELD-BDJSPA', 'disponible', NULL, NULL, NULL, true),
    ('CABINA I', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-CABIN01', 'disponible', NULL, NULL, NULL, true),
    ('CABINA II', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-CABIN02', 'disponible', NULL, NULL, NULL, true),
    ('CABINA III', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-CABIN03', 'disponible', NULL, NULL, NULL, true),
    ('CABINA IV', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-CABIN04', 'disponible', NULL, NULL, NULL, true),
    ('CABINA IX', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-CABIN09', 'disponible', NULL, NULL, NULL, true),
    ('CABINA V', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-CABIN05', 'disponible', NULL, NULL, NULL, true),
    ('CABINA VI', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-CABIN06', 'disponible', NULL, NULL, NULL, true),
    ('CABINA VII', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-CABIN07', 'disponible', NULL, NULL, NULL, true),
    ('CABINA VIII', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-CABIN08', 'disponible', NULL, NULL, NULL, true),
    ('CABINA X', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-CABIN10', 'disponible', NULL, NULL, NULL, true),
    ('CABINA XI', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-CABIN11', 'disponible', NULL, NULL, NULL, true),
    ('JACUZZI CABINA XI', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-CABIN11-JACC11', 'disponible', NULL, NULL, NULL, true),
    ('BANO CABALLEROS XI', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-CABIN11-BCCB11', 'disponible', NULL, NULL, NULL, true),
    ('CABINA XII', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-CABIN12', 'disponible', NULL, NULL, NULL, true),
    ('JACUZZI CABINA XII', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-CABIN12-JACC12', 'disponible', NULL, NULL, NULL, true),
    ('BANO CABALLEROS XII', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-CABIN12-BCCB12', 'disponible', NULL, NULL, NULL, true),
    ('CANAL DE NADO', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-CANDNAD', 'disponible', NULL, NULL, NULL, true),
    ('CUARTO DE FILTRO MUROS LLORONES', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-CFLMLLO', 'disponible', NULL, NULL, NULL, true),
    ('OFICINA GERENTE SPA', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-OFIGSPA', 'disponible', NULL, NULL, NULL, true),
    ('SALON DE BELLEZA', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-SLNBELL', 'disponible', NULL, NULL, NULL, true),
    ('TEMAZCAL', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-TEMAZCL', 'disponible', NULL, NULL, NULL, true),
    ('TIENDA SPA', 1, 'comun', 'Código técnico: J-LO-SJAS-NIV1S-TIENSPA', 'disponible', NULL, NULL, NULL, true),
    ('RESTAURANT CAFE DES ARTISTES', 1, 'comun', 'Código técnico: J-LO-RTCA', 'disponible', NULL, NULL, NULL, true),
    ('NIVEL 1 CDA', 1, 'comun', 'Código técnico: J-LO-RTCA-NIVCA', 'disponible', NULL, NULL, NULL, true),
    ('AREA PREPARACION CDA', 1, 'comun', 'Código técnico: J-LO-RTCA-NIVCA-AREPCDA', 'disponible', NULL, NULL, NULL, true),
    ('BAR CDA', 1, 'comun', 'Código técnico: J-LO-RTCA-NIVCA-BARCDAR', 'disponible', NULL, NULL, NULL, true),
    ('CAJA CDA', 1, 'comun', 'Código técnico: J-LO-RTCA-NIVCA-CAJACDA', 'disponible', NULL, NULL, NULL, true),
    ('CARCAMO CAFE DES ARTISTES', 1, 'comun', 'Código técnico: J-LO-RTCA-NIVCA-CRCMCDA', 'disponible', NULL, NULL, NULL, true),
    ('AREA DE COCHAMBRE CDA', 1, 'comun', 'Código técnico: J-LO-RTCA-NIVCA-ARECCDA', 'disponible', NULL, NULL, NULL, true),
    ('COCINA CDA', 1, 'comun', 'Código técnico: J-LO-RTCA-NIVCA-COCICDA', 'disponible', NULL, NULL, NULL, true),
    ('CUARTOS DE SECOS CDA', 1, 'comun', 'Código técnico: J-LO-RTCA-NIVCA-CTOSCDA', 'disponible', NULL, NULL, NULL, true),
    ('ESPEJO DE AGUA CDA', 1, 'comun', 'Código técnico: J-LO-RTCA-NIVCA-ESPACDA', 'disponible', NULL, NULL, NULL, true),
    ('FACHADA LADO ESPEJO DE AGUA', 1, 'comun', 'Código técnico: J-LO-RTCA-NIVCA-FALESPA', 'disponible', NULL, NULL, NULL, true),
    ('JARDINERAS CDA LADO ADULTOS', 1, 'comun', 'Código técnico: J-LO-RTCA-NIVCA-JARDCDA', 'disponible', NULL, NULL, NULL, true),
    ('OFICINA CDA', 1, 'comun', 'Código técnico: J-LO-RTCA-NIVCA-OFICDAR', 'disponible', NULL, NULL, NULL, true),
    ('PANADERIA CDA', 1, 'comun', 'Código técnico: J-LO-RTCA-NIVCA-PANADCA', 'disponible', NULL, NULL, NULL, true),
    ('PRIVADO MESA DEL CHEF CDA', 1, 'comun', 'Código técnico: J-LO-RTCA-NIVCA-PRIVCDA', 'disponible', NULL, NULL, NULL, true),
    ('SALON CDA', 1, 'comun', 'Código técnico: J-LO-RTCA-NIVCA-SLNCDAR', 'disponible', NULL, NULL, NULL, true),
    ('TERRAZA CDA', 1, 'comun', 'Código técnico: J-LO-RTCA-NIVCA-TZACDAR', 'disponible', NULL, NULL, NULL, true),
    ('BANO CABALLEROS CDA', 1, 'comun', 'Código técnico: J-LO-RTCA-NIVCA-BCCDART', 'disponible', NULL, NULL, NULL, true),
    ('BANO DAMAS CDA', 1, 'comun', 'Código técnico: J-LO-RTCA-NIVCA-BDCDART', 'disponible', NULL, NULL, NULL, true),
    ('MEZZANINE CDA', 1, 'comun', 'Código técnico: J-LO-RTCA-NIVCA-MEZZACA', 'disponible', NULL, NULL, NULL, true),
    ('EDIFICIO CASA MAAT', 1, 'comun', 'Código técnico: J-LO-ECAM', 'disponible', NULL, NULL, NULL, true),
    ('FACHADA CASA MAAT', 1, 'comun', 'Código técnico: J-LO-ECAM-FAEXG', 'disponible', NULL, NULL, NULL, true),
    ('AZOTEA CASA MAAT', 1, 'comun', 'Código técnico: J-LO-ECAM-AZCAM', 'disponible', NULL, NULL, NULL, true),
    ('NIVEL 1G', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV1G', 'disponible', NULL, NULL, NULL, true),
    ('BODEGA AYB CASA MAAT', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV1G-BODABCM', 'disponible', NULL, NULL, NULL, true),
    ('CUARTO DE FILTRO CASA MAAT', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV1G-CFLCAMA', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G101', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV1G-HAB7101', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G102', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV1G-HAB7102', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G103', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV1G-HAB7103', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G104', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV1G-HAB7104', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G105', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV1G-HAB7105', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G106', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV1G-HAB7106', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G107', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV1G-HAB7107', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G108', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV1G-HAB7108', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G109', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV1G-HAB7109', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G110', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV1G-HAB7110', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G111', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV1G-HAB7111', 'disponible', NULL, NULL, NULL, true),
    ('GAME ROOM', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV1G-GAMEROM', 'disponible', NULL, NULL, NULL, true),
    ('BANO CABALLEROS GAME ROOM', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV1G-GAMEROM-BCGARO', 'disponible', NULL, NULL, NULL, true),
    ('BANO DAMAS GAME ROOM', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV1G-GAMEROM-BDGARO', 'disponible', NULL, NULL, NULL, true),
    ('LOUNGE MAYMA', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV1G-LAUMAYM', 'disponible', NULL, NULL, NULL, true),
    ('ESCALERAS TRASERAS MAYMA', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV1G-LAUMAYM-ESTMAY', 'disponible', NULL, NULL, NULL, true),
    ('JARDIN MAGUEYES MAYMA', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV1G-LAUMAYM-JARMAY', 'disponible', NULL, NULL, NULL, true),
    ('BANO CABALLEROS MAYMA', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV1G-LAUMAYM-BCMAYM', 'disponible', NULL, NULL, NULL, true),
    ('BANO DAMAS MAYMA', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV1G-LAUMAYM-BDMAYM', 'disponible', NULL, NULL, NULL, true),
    ('PANTRY CASA MAAT', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV1G-PANTRYC', 'disponible', NULL, NULL, NULL, true),
    ('ROPERIA NIVEL 1G', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV1G-ROP1CAM', 'disponible', NULL, NULL, NULL, true),
    ('NIVEL 2G', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV2G', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G201', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV2G-HAB7201', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G202', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV2G-HAB7202', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G203', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV2G-HAB7203', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G204', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV2G-HAB7204', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G205', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV2G-HAB7205', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G206', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV2G-HAB7206', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G207', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV2G-HAB7207', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G208', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV2G-HAB7208', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G209', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV2G-HAB7209', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G210', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV2G-HAB7210', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G211', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV2G-HAB7211', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G212', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV2G-HAB7212', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G213', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV2G-HAB7213', 'disponible', NULL, NULL, NULL, true),
    ('SALA DE JUNTAS KUMAT', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV2G-SALJKUM', 'disponible', NULL, NULL, NULL, true),
    ('CINE KUMAT', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV2G-SALJKUM-CINKUM', 'disponible', NULL, NULL, NULL, true),
    ('SALA KUMAT', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV2G-SALJKUM-SALKUM', 'disponible', NULL, NULL, NULL, true),
    ('SALA VIP KUMAT', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV2G-SALJKUM-SALVKU', 'disponible', NULL, NULL, NULL, true),
    ('BANO CABALLEROS KUMAT', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV2G-SALJKUM-BCKUMA', 'disponible', NULL, NULL, NULL, true),
    ('BANO DAMAS KUMAT', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV2G-SALJKUM-BDKUMA', 'disponible', NULL, NULL, NULL, true),
    ('OFICINA MAYORDOMOS', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV2G-OFIMAYO', 'disponible', NULL, NULL, NULL, true),
    ('ROPERIA NIVEL 2G', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV2G-ROP2CAM', 'disponible', NULL, NULL, NULL, true),
    ('NIVEL 3G', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV3G', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G301', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV3G-HAB7301', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G302', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV3G-HAB7302', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G303', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV3G-HAB7303', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G304', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV3G-HAB7304', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G305', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV3G-HAB7305', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G306', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV3G-HAB7306', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G307', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV3G-HAB7307', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G308', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV3G-HAB7308', 'disponible', NULL, NULL, NULL, true),
    ('LOBBY CASA MAAT', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV3G-LOBBYCM', 'disponible', NULL, NULL, NULL, true),
    ('ESPEJO GRIFFIN', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV3G-LOBBYCM-ESPCAM', 'disponible', NULL, NULL, NULL, true),
    ('BANO CABALLEROS LOBBY CASA MAAT', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV3G-LOBBYCM-BCLOCM', 'disponible', NULL, NULL, NULL, true),
    ('ROPERIA NIVEL 3G', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV3G-ROP3CAM', 'disponible', NULL, NULL, NULL, true),
    ('NIVEL 4G', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV4G', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G401', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV4G-HAB7401', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G402', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV4G-HAB7402', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G403', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV4G-HAB7403', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G404', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV4G-HAB7404', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G405', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV4G-HAB7405', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G406', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV4G-HAB7406', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G407', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV4G-HAB7407', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G408 SUITE GOBERNADOR', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV4G-HAB7408', 'disponible', NULL, NULL, NULL, true),
    ('JACUZZI GOBERNADOR', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV4G-HAB7408-JACGOB', 'disponible', NULL, NULL, NULL, true),
    ('ROPERIA NIVEL 4G', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV4G-ROP4CAM', 'disponible', NULL, NULL, NULL, true),
    ('NIVEL 5G', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV5G', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G501', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV5G-HAB7501', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G502', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV5G-HAB7502', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G503', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV5G-HAB7503', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G504', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV5G-HAB7504', 'disponible', NULL, NULL, NULL, true),
    ('HABITACION G505 SUITE PRESIDENCIAL', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV5G-HAB7505', 'disponible', NULL, NULL, NULL, true),
    ('ALBERCA PRESIDENCIAL', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV5G-HAB7505-ALBPRE', 'disponible', NULL, NULL, NULL, true),
    ('JACUZZI PRESIDENCIAL', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV5G-HAB7505-JACPRE', 'disponible', NULL, NULL, NULL, true),
    ('ROPERIA NIVEL 5G', 1, 'comun', 'Código técnico: J-LO-ECAM-NIV5G-ROP5CAM', 'disponible', NULL, NULL, NULL, true),
    ('AREAS GENERALES CASA MAAT', 1, 'comun', 'Código técnico: J-LO-AGCM', 'disponible', NULL, NULL, NULL, true),
    ('NIVEL 1 AREAS CASA MAAT', 1, 'comun', 'Código técnico: J-LO-AGCM-NIV1M', 'disponible', NULL, NULL, NULL, true),
    ('ALBERCA CASA MAAT', 1, 'comun', 'Código técnico: J-LO-AGCM-NIV1M-ALBCAMA', 'disponible', NULL, NULL, NULL, true),
    ('CARCAMO CASA MAAT', 1, 'comun', 'Código técnico: J-LO-AGCM-NIV1M-CRCMCAM', 'disponible', NULL, NULL, NULL, true),
    ('DUELA CASA MAAT', 1, 'comun', 'Código técnico: J-LO-AGCM-NIV1M-DUELCAM', 'disponible', NULL, NULL, NULL, true),
    ('JACUZZI CASA MAAT', 1, 'comun', 'Código técnico: J-LO-AGCM-NIV1M-JACCAMA', 'disponible', NULL, NULL, NULL, true),
    ('JARDINES CASA MAAT', 1, 'comun', 'Código técnico: J-LO-AGCM-NIV1M-JARCAMA', 'disponible', NULL, NULL, NULL, true),
    ('MURO DIVISION CASA MAAT', 1, 'comun', 'Código técnico: J-LO-AGCM-NIV1M-MRDIVCM', 'disponible', NULL, NULL, NULL, true),
    ('PASILLO CONTRA CASA MAAT', 1, 'comun', 'Código técnico: J-LO-AGCM-NIV1M-PASICAM', 'disponible', NULL, NULL, NULL, true),
    ('PASILLO MAAT ACCESO RAMPA', 1, 'comun', 'Código técnico: J-LO-AGCM-NIV1M-PASIRAM', 'disponible', NULL, NULL, NULL, true),
    ('BANO CABALLEROS POOL CASA MAAT', 1, 'comun', 'Código técnico: J-LO-AGCM-NIV1M-BCPOCAM', 'disponible', NULL, NULL, NULL, true),
    ('BANO DAMAS POOL CASA MAAT', 1, 'comun', 'Código técnico: J-LO-AGCM-NIV1M-BDPOCAM', 'disponible', NULL, NULL, NULL, true);

-- Paso 4: Verificar los datos insertados
SELECT 
    id,
    nombre,
    edificio_id,
    (SELECT nombre FROM edificios WHERE id = espacios_comunes.edificio_id) as edificio_nombre,
    tipo,
    estado,
    capacidad,
    horario_apertura,
    horario_cierre,
    activo,
    created_at
FROM espacios_comunes
ORDER BY id;

-- Si todo está correcto, hacer COMMIT
-- Si hay algún error, hacer ROLLBACK
COMMIT;
